GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/15

###

POST http://localhost:3000/subscribers/66
Content-Type: application/json


 {   "name":"deniz",
    "subscribedToChannel":"sahin"
 }
 